# Site settings
title: Music Encoding Initiative
email: info@music-encoding.org
baseurl: ""
style_baseurl: ""
url: "http://music-encoding.org" # the base hostname & protocol for your site
twitter_username: music-encoding

# Build settings
markdown: kramdown

plugins:
  - jekyll-redirect-from

menu:
    - id: about
      label: 'About'
      url: '/about'
    - id: community
      label: 'Community'
      url: '/community'
      submenu:
          - id: projects
            label: 'Projects / Users'
            url: '/projects-users.html'
          - id: news
            label: 'News / Events'
            url: '/news-events.html'
          - id: mailinglist
            label: 'Mailing List'
            url: '/mailing-list.html'
          - id: interestgroups
            label: 'Interest Groups'
            url: '/interest-groups.html'
          - id: technicalteams
            label: 'Technical Team'
            url: '/technical-team.html'
          - id: meiboard
            label: 'MEI Board'
            url: '/mei-board.html'
          - id: meibylaws
            label: 'MEI By-laws'
            url: '/mei-by-laws.html'
    - id: conference
      label: 'Conference'
      url: '/conference'
      submenu:
          - id: upcoming
            label: 'MEC 2019'
            url: '/2019'
          - id: previous
            label: 'Past Conferences'
            url: '/past.html'
          - id: hosting
            label: 'Hosting Guidelines'
            url: '/hosting-guidelines.html'
    - id: resources
      label: 'Resources'
      url: '/resources'
      submenu:
          - id: introduction
            label: 'Introduction'
            url: '/introduction.html'
          - id: tools
            label: 'Tools'
            url: '/tools.html'
          - id: bibliography
            label: 'Bibliography'
            url: '/bibliography.html'
    - id: documentation
      label: 'Documentation'
      url: '/guidelines'
    - id: archive
      label: 'Archive'
      url: '/archive'

sidemenu:
    - id: conference
      label: 'Support'
      content:
          - id: about
            label: 'About'
            url: '/conference/2019/'
          - id: program
            label: 'Program'
            url: '/conference/2019/program'
          #- id: maps
            #label: 'Maps and Dining'
            #url: '/conference/2019/maps'
          #- id: travel
            #label: 'Travel and Accommodation'
            #url: #'/conference/2019/travel'
          - id: call
            label: 'Call for proposals'
            url: #'/conference/2019/call'

collections:
  projects:
    output: true
    permalink: /:collection/:name
