# Site settings
title: Music Encoding Initiative
email: info@music-encoding.org
baseurl: ""
style_baseurl: ""
url: "http://music-encoding.org" # the base hostname & protocol for your site
twitter_username: music-encoding

# Build settings
markdown: kramdown
repository: "music-encoding/music-encoding.github.io"

plugins:
  - jekyll-redirect-from

menu:
    - id: about
      label: 'About'
      url: '/about'
    - id: community
      label: 'Community'
      url: '/community'
      submenu:
          - id: projects
            label: 'Projects / Users'
            url: '/projects-users.html'
          - id: news
            label: 'News / Events'
            url: '/news-events.html'
          - id: communitycontacts
            label: 'Community Contacts'
            url: '/community-contacts.html'
          - id: interestgroups
            label: 'Interest Groups'
            url: '/interest-groups.html'
          - id: technicalteams
            label: 'Technical Team'
            url: '/technical-team.html'
          - id: meiboard
            label: 'MEI Board'
            url: '/mei-board.html'
          - id: meibylaws
            label: 'MEI By-laws'
            url: '/mei-by-laws.html'
    - id: conference
      label: 'Conference'
      url: '/conference'
      submenu:
          - id: upcoming
            label: 'MEC 2022'
            url: '/2022'
          - id: previous
            label: 'Past Conferences'
            url: '/past.html'
          - id: proceedings
            label: 'Proceedings'
            url: '/proceedings.html'
          - id: hosting
            label: 'Hosting Guidelines'
            url: '/hosting-guidelines.html'
          - id: code-of-conduct
            label: 'Code of conduct'
            url: '/code-of-conduct.html'        
    - id: resources
      label: 'Resources'
      url: '/resources'
      submenu:
          - id: background
            label: 'Background'
            url: '/background.html'
          - id: bibliography
            label: 'Bibliography'
            url: '/bibliography.html'
          - id: pedagogy
            label: 'Pedagogy & Praxis'
            url: '/pedagogy.html'
          - id: schemas
            label: 'Schemas and Namespace'
            url: '/schemas.html'
          - id: tools
            label: 'Tools'
            url: '/tools.html'
          - id: tutorials
            label: 'Tutorials'
            url: '/tutorials.html'
    - id: documentation
      label: 'Documentation'
      submenu:
          - id: guidelines-v4
            label: 'MEI 4 (latest release)'
            url: '/guidelines/v4'
          - id: guidelines-dev
            label: 'Development version'
            url: '/guidelines/dev'
          - id: guidelines-v3
            label: 'MEI 3'
            url: '/guidelines/v3'
    - id: archive
      label: 'Archive'
      url: '/archive'

collections:
  projects:
    output: true
    permalink: /:collection/:name
  tutorials:
    output: true
    permalink: /:collection/:name
  conferences:
    output: true
    permalink: /:collection/:name
